import { readFile, writeFile } from 'node:fs/promises';
export async function writeNotices() {
  const dependency = JSON.parse(await readFile(new URL('../node_modules/jose/package.json', import.meta.url), 'utf8'));
  const license = await readFile(new URL('../node_modules/jose/LICENSE.md', import.meta.url), 'utf8');
  await writeFile(new URL('../THIRD_PARTY_NOTICES.md', import.meta.url), `# Third-party notices\n\nThe extension bundles jose ${dependency.version}, licensed under MIT.\nSource: https://github.com/panva/jose\n\nBuild and test dependencies are not bundled in the VSIX. Their notices remain in their npm distributions. This file is regenerated by the build.\n\n## jose licence\n\n${license}`);
}
